spring:
   datasource:
     url: jdbc:mariadb://127.0.0.1:3306
     driver-class-name: org.mariadb.jdbc.Driver
     username: root
     password: root
     hikari:
       connection-timeout: 3000
       validation-timeout: 3000
       minimum-idle: 5
       max-lifetime: 240000
       maximum-pool-size: 20
   jpa:
      open-in-view: false
   batch:
     initialize-schema: never
     job:
      enabled: false
